-- Create "users" table
CREATE TABLE "public"."users" ("id" serial NOT NULL, "email" character varying(255) NOT NULL, "username" character varying(100) NULL, "password_hash" character varying(255) NULL, "first_name" character varying(100) NULL, "last_name" character varying(100) NULL, "email_verified" boolean NOT NULL, "is_active" boolean NOT NULL, "avatar_url" character varying(500) NULL, "google_id" character varying(255) NULL, "token_version" integer NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "users_google_id_key" UNIQUE ("google_id"), CONSTRAINT "users_username_key" UNIQUE ("username"));
-- Create index "ix_users_email" to table: "users"
CREATE UNIQUE INDEX "ix_users_email" ON "public"."users" ("email");
-- Create "subvariant_history" table
CREATE TABLE "public"."subvariant_history" ("history_id" serial NOT NULL, "id" integer NOT NULL, "variant_id" integer NOT NULL, "sku" character varying(100) NOT NULL, "subvariant_name" character varying(255) NOT NULL, "price" numeric(10,2) NULL, "stock" integer NOT NULL, "attributes" json NOT NULL, "is_default" boolean NOT NULL, "is_active" boolean NOT NULL, "version" integer NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "operation" character varying(20) NOT NULL, "changed_by" integer NULL, "changed_at" timestamptz NOT NULL, PRIMARY KEY ("history_id"));
-- Create "product_history" table
CREATE TABLE "public"."product_history" ("history_id" serial NOT NULL, "id" integer NOT NULL, "seller_id" integer NOT NULL, "name" character varying(255) NOT NULL, "description" text NULL, "category" character varying(100) NULL, "status" character varying(20) NOT NULL, "is_active" boolean NOT NULL, "version" integer NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "operation" character varying(20) NOT NULL, "changed_by" integer NULL, "changed_at" timestamptz NOT NULL, PRIMARY KEY ("history_id"));
-- Create "variant_history" table
CREATE TABLE "public"."variant_history" ("history_id" serial NOT NULL, "id" integer NOT NULL, "product_id" integer NOT NULL, "sku" character varying(100) NOT NULL, "variant_name" character varying(255) NOT NULL, "price" numeric(10,2) NOT NULL, "compare_at_price" numeric(10,2) NULL, "stock" integer NOT NULL, "attributes" json NOT NULL, "is_default" boolean NOT NULL, "is_active" boolean NOT NULL, "version" integer NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "operation" character varying(20) NOT NULL, "changed_by" integer NULL, "changed_at" timestamptz NOT NULL, PRIMARY KEY ("history_id"));
-- Create "token_blacklist" table
CREATE TABLE "public"."token_blacklist" ("jti" character varying(64) NOT NULL, "expires_at" timestamptz NOT NULL, PRIMARY KEY ("jti"));
-- Create "addresses" table
CREATE TABLE "public"."addresses" ("id" serial NOT NULL, "user_id" integer NOT NULL, "full_name" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "street" character varying(255) NOT NULL, "city" character varying(100) NOT NULL, "state" character varying(100) NULL, "postal_code" character varying(20) NOT NULL, "country" character varying(100) NOT NULL, "is_default" boolean NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "addresses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "restriction_reasons" table
CREATE TABLE "public"."restriction_reasons" ("id" serial NOT NULL, "reason_text" character varying(255) NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "sellers" table
CREATE TABLE "public"."sellers" ("user_id" integer NOT NULL, "shop_name" character varying(255) NOT NULL, "shop_description" text NULL, "payout_account" character varying(255) NULL, "is_active" boolean NOT NULL, "verification_status" character varying(20) NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("user_id"), CONSTRAINT "sellers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "products" table
CREATE TABLE "public"."products" ("id" serial NOT NULL, "seller_id" integer NOT NULL, "name" character varying(255) NOT NULL, "description" text NULL, "category" character varying(100) NULL, "status" character varying(20) NOT NULL, "is_active" boolean NOT NULL, "version" integer NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "products_seller_id_fkey" FOREIGN KEY ("seller_id") REFERENCES "public"."sellers" ("user_id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "reports" table
CREATE TABLE "public"."reports" ("id" serial NOT NULL, "reporter_id" integer NOT NULL, "product_id" integer NOT NULL, "reason_text" text NOT NULL, "version_vector" json NOT NULL, "status" character varying(20) NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "reports_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "reports_reporter_id_fkey" FOREIGN KEY ("reporter_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "restrictions" table
CREATE TABLE "public"."restrictions" ("id" serial NOT NULL, "user_id" integer NOT NULL, "restricted_by" integer NOT NULL, "report_id" integer NULL, "reason_id" integer NOT NULL, "description" text NULL, "penalty_days" integer NULL, "status" character varying(20) NOT NULL, "created_at" timestamptz NOT NULL, "lifted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "restrictions_reason_id_fkey" FOREIGN KEY ("reason_id") REFERENCES "public"."restriction_reasons" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "restrictions_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "public"."reports" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "restrictions_restricted_by_fkey" FOREIGN KEY ("restricted_by") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "restrictions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "appeals" table
CREATE TABLE "public"."appeals" ("id" serial NOT NULL, "restriction_id" integer NOT NULL, "user_id" integer NOT NULL, "appeal_text" text NOT NULL, "status" character varying(20) NOT NULL, "reviewed_by" integer NULL, "created_at" timestamptz NOT NULL, "reviewed_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "appeals_restriction_id_fkey" FOREIGN KEY ("restriction_id") REFERENCES "public"."restrictions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "appeals_reviewed_by_fkey" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "appeals_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "carts" table
CREATE TABLE "public"."carts" ("id" serial NOT NULL, "user_id" integer NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "carts_user_id_key" UNIQUE ("user_id"), CONSTRAINT "carts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "product_variants" table
CREATE TABLE "public"."product_variants" ("id" serial NOT NULL, "product_id" integer NOT NULL, "sku" character varying(100) NOT NULL, "variant_name" character varying(255) NOT NULL, "price" numeric(10,2) NOT NULL, "compare_at_price" numeric(10,2) NULL, "stock" integer NOT NULL, "attributes" json NOT NULL, "is_default" boolean NOT NULL, "is_active" boolean NOT NULL, "version" integer NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "product_variants_product_id_sku_key" UNIQUE ("product_id", "sku"), CONSTRAINT "product_variants_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "product_subvariants" table
CREATE TABLE "public"."product_subvariants" ("id" serial NOT NULL, "variant_id" integer NOT NULL, "sku" character varying(100) NOT NULL, "subvariant_name" character varying(255) NOT NULL, "price" numeric(10,2) NULL, "stock" integer NOT NULL, "attributes" json NOT NULL, "is_default" boolean NOT NULL, "is_active" boolean NOT NULL, "version" integer NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "product_subvariants_variant_id_sku_key" UNIQUE ("variant_id", "sku"), CONSTRAINT "product_subvariants_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."product_variants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "cart_items" table
CREATE TABLE "public"."cart_items" ("id" serial NOT NULL, "cart_id" integer NOT NULL, "subvariant_id" integer NOT NULL, "quantity" integer NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "cart_items_cart_id_subvariant_id_key" UNIQUE ("cart_id", "subvariant_id"), CONSTRAINT "cart_items_cart_id_fkey" FOREIGN KEY ("cart_id") REFERENCES "public"."carts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "cart_items_subvariant_id_fkey" FOREIGN KEY ("subvariant_id") REFERENCES "public"."product_subvariants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "orders" table
CREATE TABLE "public"."orders" ("id" serial NOT NULL, "user_id" integer NOT NULL, "address_id" integer NOT NULL, "status" character varying(20) NOT NULL, "payment_status" character varying(20) NOT NULL, "subtotal" numeric(10,2) NOT NULL, "shipping_cost" numeric(10,2) NOT NULL, "total" numeric(10,2) NOT NULL, "notes" text NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "orders_address_id_fkey" FOREIGN KEY ("address_id") REFERENCES "public"."addresses" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "orders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "order_items" table
CREATE TABLE "public"."order_items" ("id" serial NOT NULL, "order_id" integer NOT NULL, "subvariant_id" integer NOT NULL, "product_name" character varying(255) NOT NULL, "variant_name" character varying(255) NOT NULL, "subvariant_name" character varying(255) NOT NULL, "variant_sku" character varying(100) NOT NULL, "attributes" json NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(10,2) NOT NULL, "total_price" numeric(10,2) NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "order_items_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "public"."orders" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "order_items_subvariant_id_fkey" FOREIGN KEY ("subvariant_id") REFERENCES "public"."product_subvariants" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "product_comments" table
CREATE TABLE "public"."product_comments" ("id" serial NOT NULL, "product_id" integer NOT NULL, "user_id" integer NOT NULL, "parent_comment_id" integer NULL, "rating" integer NULL, "content" text NOT NULL, "status" character varying(20) NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "product_comments_parent_comment_id_fkey" FOREIGN KEY ("parent_comment_id") REFERENCES "public"."product_comments" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "product_comments_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "product_comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "product_images" table
CREATE TABLE "public"."product_images" ("id" serial NOT NULL, "product_id" integer NOT NULL, "variant_id" integer NULL, "subvariant_id" integer NULL, "url" character varying(500) NOT NULL, "alt_text" character varying(255) NULL, "is_main" boolean NOT NULL, "created_at" timestamptz NOT NULL, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_at" timestamptz NULL, PRIMARY KEY ("id"), CONSTRAINT "product_images_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "public"."products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "product_images_subvariant_id_fkey" FOREIGN KEY ("subvariant_id") REFERENCES "public"."product_subvariants" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "product_images_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "public"."product_variants" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "refresh_tokens" table
CREATE TABLE "public"."refresh_tokens" ("id" serial NOT NULL, "user_id" integer NOT NULL, "token_hash" character varying(64) NOT NULL, "expires_at" timestamptz NOT NULL, "revoked" boolean NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "refresh_tokens_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "ix_refresh_tokens_token_hash" to table: "refresh_tokens"
CREATE UNIQUE INDEX "ix_refresh_tokens_token_hash" ON "public"."refresh_tokens" ("token_hash");
-- Create "restriction_products" table
CREATE TABLE "public"."restriction_products" ("id" serial NOT NULL, "restriction_id" integer NOT NULL, "subvariant_id" integer NULL, "version_snapshot" json NOT NULL, "note" text NULL, PRIMARY KEY ("id"), CONSTRAINT "restriction_products_restriction_id_fkey" FOREIGN KEY ("restriction_id") REFERENCES "public"."restrictions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "restriction_products_subvariant_id_fkey" FOREIGN KEY ("subvariant_id") REFERENCES "public"."product_subvariants" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "roles" table
CREATE TABLE "public"."roles" ("id" integer NOT NULL, "name" character varying(50) NOT NULL, "description" character varying(255) NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "roles_name_key" UNIQUE ("name"));
-- Create "user_roles" table
CREATE TABLE "public"."user_roles" ("user_id" integer NOT NULL, "role_id" integer NOT NULL, "assigned_by" integer NULL, "assigned_at" timestamptz NOT NULL, PRIMARY KEY ("user_id", "role_id"), CONSTRAINT "user_roles_assigned_by_fkey" FOREIGN KEY ("assigned_by") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."roles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "wishlists" table
CREATE TABLE "public"."wishlists" ("id" serial NOT NULL, "user_id" integer NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "wishlists_user_id_key" UNIQUE ("user_id"), CONSTRAINT "wishlists_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "wishlist_items" table
CREATE TABLE "public"."wishlist_items" ("id" serial NOT NULL, "wishlist_id" integer NOT NULL, "subvariant_id" integer NOT NULL, "added_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "wishlist_items_wishlist_id_subvariant_id_key" UNIQUE ("wishlist_id", "subvariant_id"), CONSTRAINT "wishlist_items_subvariant_id_fkey" FOREIGN KEY ("subvariant_id") REFERENCES "public"."product_subvariants" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "wishlist_items_wishlist_id_fkey" FOREIGN KEY ("wishlist_id") REFERENCES "public"."wishlists" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
